spring:
  application:
    name: Utilities
  devtools:
    restart:
      enabled: true
      trigger-file: .reloadTrigger
      poll-interval: 400ms
      quiet-period: 1ms
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    #path: /swagger-ui/index.html
    operationSorter: method
    enabled: true
  api-docs:
    path: /api-docs
  packages-to-scan: com.cando.utilities.resources

server:
  port: 8082

service:
  certificate:
    keystore-extension: pfx, jks, p12
    token-extension: jwt, jose
  home-page: http://localhost:8082/home/